#!/usr/bin/env bash

function crawl_derivations {
    envArgs=(-qa --meta --json)
    IFS='#' read -r flakeURI flakeAttr <<< "$1"
    shift
    echo $flakeURI $flakeAttr
    if [ ! -z "$flakeAttr" ]; then
        envArgs+=(-A "$flakeAttr"); shift
    fi
    tmpfile=$(mktemp).nix
    cat <<EOF > $tmpfile
        builtins.getFlake "$flakeURI"
EOF
    envArgs+=(-f $tmpfile)
    nix-env "${envArgs[@]}" "$@"
}

function crawl_options {
    IFS='#' read -r flakeURI flakeAttr <<< "$1"
    shift
    echo $flakeURI $flakeAttr
    tmpfile=$(mktemp).nix
    cat <<EOF > $tmpfile
    let
        pkgs = import <nixpkgs> {};
        flake = builtins.getFlake "$flakeURI";
        doc = pkgs.nixosOptionsDoc { inherit (flake.$flakeAttr) options; };
    in doc.optionsNix
EOF

    nix eval -f $tmpfile --json "$@"
}

